on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - uses: actions/checkout@v2

      - name: Generate
        run: go generate ./...

      - name: Check for changes
        run: git diff --exit-code

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
