name: main

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - uses: actions/checkout@v2

      - name: Generate
        run: |
          go generate ./...
          git diff --exit-code

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...

      - name: Install Lint Tools
        working-directory: /
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          go get golang.org/x/lint/golint

      - name: Lint
        run: |
          $(go env GOPATH)/bin/staticcheck ./...
          $(go env GOPATH)/bin/golint ./...
          go vet

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - uses: actions/checkout@v2

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo snap install goreleaser --classic
          goreleaser release
